.circleci/config.yml
README.md

BREAKING CHANGE: bump major to reflect new process

chore: add v to tag

---

radar/languages_frameworks/spring_boot2.yaml
radar/languages_frameworks/vertx.yaml

add vert.x to languages & framework section

feat: add vert.x

---

radar/data_management/mysql.yaml

Description and rationale for MySQL being on `HOLD`.

fix: Add rationale for MySQL

---

radar/languages_frameworks/pact.yaml
radar/languages_frameworks/spring_cloud_contract.yaml
radar/techniques/consumer_contract_testing.yaml

Updated description for `Spring Cloud Contract` and added two more blips for consumer-driven contract testing.

feat: Add consumer-driven contract testing

---

radar/infrastructure_config/kubernetes.yaml
radar/languages_frameworks/angularjs.yaml
radar/languages_frameworks/pact.yaml
radar/languages_frameworks/spring_cloud_contract.yaml
radar/techniques/consumer_contract_testing.yaml

Collection of 3 Tech Radar updates.

Tech Radar 2.3.0

---

radar/infrastructure_config/bitbucket.yaml

This is a whitespace fix for Jarles pull request

feat: add Bitbucket

---

radar/data_management/beats.yaml
radar/data_management/elasticsearch.yaml
radar/data_management/kibana.yaml
radar/data_management/logstash.yaml

Updated related information on the ELK stack.

---

.dockerignore
.nginx.conf
Dockerfile
src/js/components/App.jsx
src/js/components/Entry.jsx
src/js/components/Footer.jsx
src/js/components/NotFound.jsx
src/js/components/Quadrant.jsx
src/js/modules/__mocks__/radarService.js
test/App.test.jsx
test/Entry.test.jsx
test/NotFound.test.jsx
test/Quadrant.test.jsx
test/__snapshots__/Entry.test.jsx.snap
test/__snapshots__/Footer.test.jsx.snap
test/__snapshots__/NotFound.test.jsx.snap
test/__snapshots__/Quadrant.test.jsx.snap

1. Added nginx configuration to redirect all requests to our app
2. Added `NotFound` component in the app to internally handle 404s
3. Fix render bug in footer

fix: Add nginx config and handle 404 in react

---

radar/infrastructure_ci_cd/cake.yaml

We are now trialing Cake in ShopNDrop and RSPOS

feat: Cake trial

---

package-lock.json

Updated dependencies to remove all security issues.

chore: Update package-lock.json to fix security issues

---

README.md
radar/dev/grial_ui_kit.yaml
src/radar_entry.schema.yaml

Add Grial UI Kit 3.0 to Development quadrant's Trial ring

feat: add Grial UI Kit

---

radar/infrastructure_ci_cd/consul.yaml
radar/qa/ardoq.yaml

Change Consul blip to Trial and added Licensing information

feat: Trial Consul blip

---

radar/dev/flyway.yaml
radar/dev/liquibase.yaml

Liquibase has been in production for many years in Extenda-POS, Selfscan and CO.

feat: Add liquibase

---

package-lock.json
radar/infrastructure_ci_cd/jib.yaml

Moves Jib to TRIAL. 
Adds line about distroless images.

feat: move Jib ASSESS -> TRIAL

---

README.md

to make a branch instead, so that pipeline will work correctly

docs: Change request from fork

---

radar/dev/flutter.yaml

This substitutes https://github.com/extenda/tech-radar/pull/111 made by @RedasP

feat: Add Flutter to ASSESS

---

.github/workflows/commit.yml
.github/workflows/pull-request.yml
cloud-run.yaml

* GitHub Actions now run on pull requests and on push to master.
* Our commitlint workflow is updated with proper event names
* Updated workflows to use our actions instead of inlined deploy commands

build: Update workflows to build on PR and merge with latest actions

---

radar/data_management/bigquery.yaml

Added the bigquery information

feat: Add bigquery as trial

---

radar/dev/Python.yaml
radar/dev/python.yaml
src/radar_entry.schema.yaml

Added the python to tech radar as trial.

feat: Add Python to TRIAL

---

radar/qa/jaeger.yaml

As discussed in architecture chapter, we want to promote the use of GCP services for Hii Retail.

feat: Move Jaeger to HOLD

---

radar/dev/xamarin_forms.yaml

Adding Xamarin Forms to Tech-Radar

feat: Add Xamarin Forms to HOLD

---

radar/qa/structurizr.yaml

See the [ADR](https://github.com/extenda/chap-architecture-docs/blob/master/adr/0008-use-structurizr-dsl-for-c4-architecture-diagrams.md) behind this adoption.

feat: Adopt Structurizr DSL

---

packages/builder/test/index.test.js

Chasing code coverage on index file.

chore: Update builder test

---

packages/app/eslint.config.js
packages/app/src/js/components/App.jsx
packages/app/webpack.config.js

Improve quality of life during development and local radar content updates.

chore: Disable google login on dev-server

---

radar/dev/enunciate.yaml
radar/dev/flatfileportal.yaml
radar/dev/git.yaml
radar/dev/grial_ui_kit.yaml
radar/dev/infragistics.yaml
radar/dev/java.yaml
radar/dev/javafx.yaml
radar/dev/jersey_v1.yaml
radar/dev/jsw.yaml
radar/dev/nativescript.yaml
radar/dev/quarkus.yaml
radar/dev/spring_framework.yaml
radar/dev/xamarin_forms.yaml

Archive radar blips in the development category that are either abandoned or no longer relevant for our future development. Blips are still accessible, just not rendered in the radar graph.

feat: Archive entries in development category

---

radar/infrastructure_ci_cd/styra_das.yaml

Move Styra DAS from adopt to hold since we've replaced it with other solutions.

feat: Hold Styra DAS
